added pass function
DurhamAcademy/FRC2024 pull request #122
Opened 2024-04-03 21:12 UTC by Ryan-Bauroth

not keyboard to a controller yet

2024-04-03 21:32 UTC, GBKP requested changes

2024-04-03 22:01 UTC, GBKP approved these changes

2024-04-04 02:17 UTC, a1cd approved these changes
i'd go a bit faster but we can change that with testing

2024-04-04 02:18 UTC, a1cd requested changes
need feed command dbchadlafkhds;lghfpaoskdgh;asdkgh;askldhg;oaskldjngalks.,jdmgn;aksdjx

2024-04-16 17:19 UTC, closed without merging